package:
    type:           project
    name:           hisite-template
    title:          HiSite Project Template
    license:        BSD-3-Clause
    headline:       HiSite
    description:    |
        HiSite is a way to build modular Yii2 projects with plugins.

        This package is a template to start your project with.

        It includes:

        - [hisite] - hisite basic project
        - [yii2-thememanager] - theme manager
        - [yii2-theme-original] - Yii2 original theme
        - [yii2-theme-flat] - flat theme
        - [yii2-pnotify] - JQuery PNotify extension
        - [yii2-language] - language switcher
        - [yii2-monitoring] - application monitoring

        The project uses [hidev] tool to automate repetitive tasks:

        - generate and update package files: README, LICENSE, .gitignore, composer.json
        - keep CHANGELOG file with [chkipper]
        - generate and deploy vhost config file
        - run standard tasks such as running tests and php-cs-fixer
        - substitute yii console script

        [hidev]:                https://hiqdev.com/packages/hidev
        [hisite]:               https://hiqdev.com/packages/hisite
        [yii2-thememanager]:    https://hiqdev.com/packages/yii2-thememanager
        [yii2-theme-original]:  https://hiqdev.com/packages/yii2-theme-original
        [yii2-theme-flat]:      https://hiqdev.com/packages/yii2-theme-flat
        [yii2-pnotify]:         https://hiqdev.com/packages/yii2-thememanager
        [yii2-language]:        https://hiqdev.com/packages/yii2-language
        [yii2-monitoring]:      https://hiqdev.com/packages/yii2-monitoring
        [chkipper]:             https://hiqdev.com/packages/chkipper

hisite:
    vhost:
        domain: hisite.hiqdev.com

vendor:
    name:           hiqdev
    title:          HiQDev
    homepage:       http://hiqdev.com/
    authors:
        hiqsol:
            name:       Andrii Vasyliev
            role:       Project lead
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   http://hipanel.com/
        SilverFire:
            name:       Dmitry Naumenko
            role:       Lead backend developer
            email:      d.naumenko.a@gmail.com
            github:     https://github.com/SilverFire
            homepage:   http://silverfire.me/
        tafid:
            name:       Andrey Klochok
            role:       Lead frontend developer
            email:      andreyklochok@gmail.com
            github:     https://github.com/tafid
            homepage:   http://hiqdev.com/
        BladeRoot:
            name:       Yuriy Myronchuk
            role:       QA Lead
            email:      bladeroot@gmail.com
            github:     https://github.com/BladeRoot
            homepage:   http://hiqdev.com/
