package:
    type:           project
    name:           hisite-template
    title:          HiSite Project Template
    headline:       HiSite Template
    license:        BSD-3-Clause
    description:    |
        [HiSite] is a base project for building modular [Yii2] web applications from plugins.

        This package is a template to start your HiSite project with.

        It includes:

        - [hisite] - HiSite basic project
        - [yii2-theme-original] - Yii2 original theme
        - [yii2-pnotify] - JQuery [PNotify] extension
        - [yii2-language] - language switcher
        - [yii2-monitoring] - application monitoring

        The project uses [hidev] tool to automate repetitive tasks:

        - generate and keep up to date package files: README, LICENSE, .gitignore, composer.json
        - keep CHANGELOG file with [chkipper]
        - generate and deploy Nginx virtual host config file
        - run standard tasks such as running tests and `php-cs-fixer`
        - substitute `yii` console script

        [yii2]:                 http://www.yiiframework.com/
        [hidev]:                https://github.com/hiqdev/hidev
        [HiSite]:               https://github.com/hiqdev/hisite
        [yii2-theme-original]:  https://github.com/hiqdev/yii2-theme-original
        [yii2-pnotify]:         https://github.com/hiqdev/yii2-thememanager
        [yii2-language]:        https://github.com/hiqdev/yii2-language
        [yii2-monitoring]:      https://github.com/hiqdev/yii2-monitoring
        [chkipper]:             https://github.com/hiqdev/chkipper
        [pnotify]:              https://github.com/sciactive/pnotify

webapp:
    vhost:
        domain: hisite.hiqdev.com

vendor:
    name:           hiqdev
    title:          HiQDev
    homepage:       http://hiqdev.com/
    authors:
        hiqsol:
            name:       Andrii Vasyliev
            role:       Project lead
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   http://hipanel.com/
        SilverFire:
            name:       Dmitry Naumenko
            role:       Lead backend developer
            email:      d.naumenko.a@gmail.com
            github:     https://github.com/SilverFire
            homepage:   http://silverfire.me/
        tafid:
            name:       Andrey Klochok
            role:       Lead frontend developer
            email:      andreyklochok@gmail.com
            github:     https://github.com/tafid
            homepage:   http://hiqdev.com/
        BladeRoot:
            name:       Yuriy Myronchuk
            role:       QA Lead
            email:      bladeroot@gmail.com
            github:     https://github.com/BladeRoot
            homepage:   http://hiqdev.com/
